# Generated by Django 5.2.1 on 2025-05-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_bloodrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='preferred_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
