services:
  - type: web
    name: fyp-project
    env: python
    buildCommand: |
      python -m venv env
      source env/bin/activate
      pip install -r requirements.txt
    startCommand: gunicorn Blood.Backend.wsgi:application --bind 0.0.0.0:8000
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Blood.Backend.settings
      - key: SECRET_KEY
        value: <your-secret-key>
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
