services:
  - type: web
    name: fyp-project
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Blood.Backend.settings
      - key: SECRET_KEY
        value: <your-secret-key>
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
